### ISSUE TITLE
Worker ID generated will always be the same if compiled to Native

### ISSUE THREAD

**Issue by sebastienblanc** [redhat-developer-demos/hybrid-cloud-app-backend#1]
https://github.com/redhat-developer-demos/hybrid-cloud-app-backend/blob/master/src/main/java/io/openshift/booster/messaging/WorkerResource.java#L19 
This needs to be changed, @kameshsampath suggested to add a AppScoped Worker Id service .

**Comment by kameshsampath** [comment]
Closing via 87f41a3
